### ISSUE TITLE
Update beta testing form for metap and genomad

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#12]

**Comment by ssarrafan** [comment]
assigned to you @ljohnson09 but let me know if it should be assigned to someone else

**Comment by ljohnson09** [comment]
@ssarrafan Julia is the task owner but we are working together to refine it. Thanks!

**Comment by ssarrafan** [comment]
Thanks for closing this issue @ljohnson09 
It would be great to add a link to the updated testing form in this issue for future reference and reporting

**Comment by ljohnson09** [comment]
https://forms.gle/hjc5TaogLNZnsQXq6 Link to beta testing form
