### ISSUE TITLE
Submission notification 

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#18]
**Deliverable this task is associated with**

_See Deliverables tab here: _ (Kitware items list) https://docs.google.com/spreadsheets/d/1t3qTjQHkghSZqb1Bvaq6NGRzyeNXHonTaZredBtoo-M/edit#gid=0 

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [ ] Update DH to have a note / info box that submissions are saved with every click to a new cell

**Criteria for completion**
- Implemented feature 

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tag issues]

**Comment by mslarae13** [comment]
@naglepuff @marySalvi 
@shreddd approved this issue and a couple others for priority between now & early May.
Can you comment on when you can start this & how many sprints will be needed to complete? And I'll update the target dates.

**Comment by naglepuff** [comment]
Instead of a static message telling the user about this, we could implement a google-drive style spinner that shows when the client has initiated a `PATCH` and turns to a checkmark once the server returns a response with the `200` status code.

**Comment by mslarae13** [comment]
Great!! Thanks Mike! Any estimate on time till implementation in dev (# of working hours & # of sprints)? (to work on sprint planning & priorities)

**Comment by naglepuff** [comment]
I'd estimate that this would take 6-10 hours and could be done in a single sprint

**Comment by aclum** [comment]
Per infrastructure sync Mary will start on this.

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.

**Comment by ssarrafan** [comment]
Moving to next sprint
Active
