### ISSUE TITLE
ORCID rerouting

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#19]
**Deliverable this task is associated with**

_See Deliverables tab here: _ https://docs.google.com/spreadsheets/d/1t3qTjQHkghSZqb1Bvaq6NGRzyeNXHonTaZredBtoo-M/edit#gid=0

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [ ] Signing in with ORCID on submission portal autoroutes you to DP, update to route back to submission portal home page

**Criteria for completion**
- Correct routing after sign-in

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by mslarae13** [comment]
@naglepuff @marySalvi 
@shreddd approved this issue and a couple others for priority between now & early May.
Can you comment on when you can start this & how many sprints will be needed to complete? And I'll update the target dates.

**Comment by naglepuff** [comment]
This might be doable using OAuth's `state` mechanism. I don't think this issue would take longer than a single sprint given current allocations (and would probably be shorter) maybe 4-12 hours. Leaving room for some uncertainty here.

**Comment by shreddd** [comment]
This will be addressed when @pkalita-lbl is done with auth updates from https://github.com/microbiomedata/nmdc-field-notes/issues/92

**Comment by mslarae13** [comment]
Sounds like @pkalita-lbl  has completed https://github.com/microbiomedata/nmdc-field-notes/issues/92

@naglepuff considering your tasks and time you're spending on berk-schema roll out, do you think this task could fit in or should we backlog it until you have more free time / completed some berk tasks?

FYI @shreddd
