### ISSUE TITLE
Write and review script for app pre-design

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#24]

**Comment by ljohnson09** [comment]
https://docs.google.com/document/d/1V9FEWft7LGOzK9Teso4Xlf6IbHEYHIjxKKF0zGMFnTo/edit#heading=h.hqaryod4rdw2

**Comment by ssarrafan** [comment]
@ljohnson09 I didn't see a script per say in the linked Google doc so I will move this to the next sprint to complete. If it's done please close the issue. Thanks.

**Comment by ljohnson09** [comment]
Mockups reviewed by team to integrate into script - moving to next sprint for team review of script next week before interviews.

**Comment by ljohnson09** [comment]
Script completed 12/7/23 after test interview edits.
