### ISSUE TITLE
Submission Portal Usability Test Research Plan

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#5]
- [x] Confirm usability test concepts/usability questions
- [x] Write script for tasks
- [x] Review script for tasks 
- [x] External review by LBL Scientific Data Division
- [x] Identify which champions or others to email
- [x] #8
- [x] #9
- [ ] Make github tickets to track implementation of insights/actions

**Comment by ssarrafan** [comment]
@ljohnson09 what's the status of this issue?  I don't see any updates for the last 2 weeks.

**Comment by ljohnson09** [comment]
Script is under review!

**Comment by ssarrafan** [comment]
@ljohnson09 should this continue to the next sprint?

**Comment by ljohnson09** [comment]
Yes, please! Thanks!

**Comment by ssarrafan** [comment]
@ljohnson09 can this issue be closed now?

**Comment by ssarrafan** [comment]
Chatted with @ljohnson09 on Slack and this issue will continue to the next sprint.

**Comment by ssarrafan** [comment]
@ljohnson09 @jkelliher-github what's the status of this issue?  Can it be closed yet?

**Comment by mslarae13** [comment]
@ssarrafan  the child issues are still live & being completed. 
IMO, better to keep the parent issue open, but I'll defer to @ljohnson09

**Comment by ssarrafan** [comment]
Moving this issue to the next sprint for the insights/actions. @ljohnson09 @jkelliher-github @mslarae13

**Comment by ssarrafan** [comment]
Team was traveling so need to move this issue one more time to the next sprint per @ljohnson09 
Moving this issue to the next sprint for the insights/actions. @ljohnson09 @jkelliher-github @mslarae13

**Comment by ljohnson09** [comment]
https://miro.com/app/board/uXjVOlmuEHE=/ Insights compilation on miro board
